### ISSUE TITLE
RQ-014 설정 화면 구현

### ISSUE THREAD

**Issue by greenlotte4** [greenlotte4/lotte-2nd-project-front-team1#27]
화면 설계를 바탕으로 설정 화면을 구현한다.
- 사용자 관련 설정 HTML 작업
- 기능 관련 설정 HTML 작업
- 요금제 관련 설정 HTML 작업
- 기타 필요한 설정 HTML 작업
- 비고 이미지 참고

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Implemented the settings page with sections for user settings, functionality settings, pricing plan settings, and other necessary settings. Updated the styling to match the existing design.

You can review changes in this commit: https://github.com/lkilu6456546/greenlotte4-lotte-2nd-project-front-team1-27/commit/221a1dfe67026efb79ab6a69cf6d65af62801ea1.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
